import { Geist, Geist_Mono } from "next/font/google";
import "@/src/app/globals.css";
import DashBoardLayout from "@/src/Layout/DashBoardLayout";
import React from "react";
import ProtectedRoute from "@/src/components/main/ProtectedRoute";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute>
      <DashBoardLayout>{children}</DashBoardLayout>
    </ProtectedRoute>
  );
}
